sonar.organization=hyrule-iac
sonar.projectKey=DevSecOps-01
sonar.projectName=DevSecOps-01
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.exclusions=**/bin/**,**/obj/**,**/wwwroot/lib/**,**/.terraform/**
sonar.scm.provider=git
