name: deploy-k3d-self-hosted

on:
  push:
    branches:
      - main
    paths:
      - "k8s/rollouts/rollout.yaml"
      - "k8s/rollouts/analysis-template.yaml"
      - ".github/workflows/deploy-k3d-self-hosted.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Apply rollout manifests to local k3d cluster
        shell: powershell
        run: |
          kubectl apply -f k8s/rollouts/
          kubectl argo rollouts get rollout demo-devsecops-api -n default
      
      - name: Diagnostic - Check Cluster availability
        shell: powershell
        run: |
          $maxRetries = 10
          for ($i=0; $i -lt $maxRetries; $i++){
            try {
              $response = Invoke-WebRequest -Uri "http://localhost:8086/health" -Method Get
              if ($response.StatusCode -eq 200) {
                Write-Host "FRANKEN-API is alive and running"
                exit 0
              } 
              } catch {
                Write-Host "Waiting for FRANKENAPI... ($i)"
                Start-Sleep -Seconds 5
                }
          }
          Write-Error "FRANKENAPI is still dead"
          exit 1