name: deploy-k3d-self-hosted

on:
  push:
    branches:
      - main
    paths:
      - "k8s/rollouts/rollout.yaml"
      - "k8s/rollouts/analysis-template.yaml"
      - ".github/workflows/deploy-k3d-self-hosted.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    env:
      KUBECONFIG: 'C:\Users\Aldo\.kube\config'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Apply rollout manifests to local k3d cluster
        shell: powershell
        run: |
          # Forzamos el uso del config que validamos en el puerto 40839
          $env:KUBECONFIG = "$env:USERPROFILE\.kube\config"
          
          # Aplicamos con --validate=false para evitar el error de conexión al descargar esquemas
          kubectl apply -f k8s/rollouts/ --validate=false
          
          # Si no tienes el binario 'kubectl-argo-rollouts', usamos el comando nativo de k8s
          # para verificar que el recurso existe.
          kubectl get rollout demo-devsecops-api -n default
      
      - name: Diagnostic - Check Cluster availability
        shell: powershell
        run: |
          $maxRetries = 12 # Aumentamos un poco por el tiempo de arranque de .NET 10
          for ($i=1; $i -le $maxRetries; $i++){
            try {
              # Nota: Asegúrate de que el Service esté mapeado al puerto 8086 de tu host
              $response = Invoke-WebRequest -Uri "http://localhost:8086/" -UseBasicParsing -Method Get
              if ($response.StatusCode -eq 200) {
                Write-Host "FRANKEN-API is alive and running!"
                exit 0
              } 
            } catch {
              Write-Host "Waiting for FRANKEN-API... Attempt $i/$maxRetries"
              Start-Sleep -Seconds 10 # .NET 10 en k3d local puede tardar unos segundos en levantar
            }
          }
          Write-Error "FRANKEN-API is still dead after check"
          exit 1